/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.saam.gestao.view;

/**
 *
 * @author Guilherme
 */
public class CadastroUsuarioView extends javax.swing.JFrame {

    private static final java.awt.Color COR_REGRA_PENDENTE = new java.awt.Color(140, 140, 140);
    private static final java.awt.Color COR_REGRA_OK = new java.awt.Color(46, 125, 50);

    private char echoCharPadrao;

    /**
     * Creates new form CadastroUsuarioView
     */
    public CadastroUsuarioView() {
        initComponents();
        com.saam.gestao.util.BordaArredondada.aplicar(txtNome, txtEmail, txtSenha, txtConfirmarSenha);
        echoCharPadrao = txtSenha.getEchoChar();
        btnMostrarSenha1.addActionListener(evt -> alternarVisibilidade(txtSenha, btnMostrarSenha1));
        btnMostrarSenha2.addActionListener(evt -> alternarVisibilidade(txtConfirmarSenha, btnMostrarSenha2));
        configurarChecklistDeSenha();
        getRootPane().setDefaultButton(btnCadastrar);
        setLocationRelativeTo(null);
    }

    private void alternarVisibilidade(javax.swing.JPasswordField campo, javax.swing.JToggleButton botao) {
        campo.setEchoChar(botao.isSelected() ? (char) 0 : echoCharPadrao);
    }

    private void configurarChecklistDeSenha() {
        txtSenha.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                atualizarChecklist();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                atualizarChecklist();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                atualizarChecklist();
            }
        });
    }

    private void atualizarChecklist() {
        String senha = new String(txtSenha.getPassword());
        marcarRegra(lblRegraTamanho, com.saam.gestao.util.PasswordPolicy.temTamanhoMinimo(senha));
        marcarRegra(lblRegraMaiuscula, com.saam.gestao.util.PasswordPolicy.temMaiuscula(senha));
        marcarRegra(lblRegraMinuscula, com.saam.gestao.util.PasswordPolicy.temMinuscula(senha));
        marcarRegra(lblRegraNumero, com.saam.gestao.util.PasswordPolicy.temNumero(senha));
        marcarRegra(lblRegraEspecial, com.saam.gestao.util.PasswordPolicy.temCaractereEspecial(senha));
    }

    private void marcarRegra(javax.swing.JLabel label, boolean atendida) {
        label.setForeground(atendida ? COR_REGRA_OK : COR_REGRA_PENDENTE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnMostrarSenha1 = new javax.swing.JToggleButton();
        lblRegraTamanho = new javax.swing.JLabel();
        lblRegraMaiuscula = new javax.swing.JLabel();
        lblRegraMinuscula = new javax.swing.JLabel();
        lblRegraNumero = new javax.swing.JLabel();
        lblRegraEspecial = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtConfirmarSenha = new javax.swing.JPasswordField();
        btnMostrarSenha2 = new javax.swing.JToggleButton();
        btnCadastrar = new com.saam.gestao.util.BotaoArredondado();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Usuário - Sistema de Gestão de Funcionários");
        setBackground(new java.awt.Color(238, 241, 251));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 208, 234)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(63, 81, 181));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Usuário");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 39, 58));
        jLabel2.setText("Nome:");

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(34, 39, 58));
        jLabel6.setText("E-mail:");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(34, 39, 58));
        jLabel7.setText("Senha:");

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnMostrarSenha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/olho.png"))); // NOI18N
        btnMostrarSenha1.setBorderPainted(false);
        btnMostrarSenha1.setContentAreaFilled(false);
        btnMostrarSenha1.setFocusPainted(false);
        btnMostrarSenha1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/olho_riscado.png"))); // NOI18N

        lblRegraTamanho.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblRegraTamanho.setForeground(new java.awt.Color(140, 140, 140));
        lblRegraTamanho.setText("• Mínimo 6 caracteres");

        lblRegraMaiuscula.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblRegraMaiuscula.setForeground(new java.awt.Color(140, 140, 140));
        lblRegraMaiuscula.setText("• 1 letra maiúscula");

        lblRegraMinuscula.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblRegraMinuscula.setForeground(new java.awt.Color(140, 140, 140));
        lblRegraMinuscula.setText("• 1 letra minúscula");

        lblRegraNumero.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblRegraNumero.setForeground(new java.awt.Color(140, 140, 140));
        lblRegraNumero.setText("• 1 número");

        lblRegraEspecial.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblRegraEspecial.setForeground(new java.awt.Color(140, 140, 140));
        lblRegraEspecial.setText("• 1 caractere especial");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(34, 39, 58));
        jLabel8.setText("Confirmar Senha:");

        txtConfirmarSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnMostrarSenha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/olho.png"))); // NOI18N
        btnMostrarSenha2.setBorderPainted(false);
        btnMostrarSenha2.setContentAreaFilled(false);
        btnMostrarSenha2.setFocusPainted(false);
        btnMostrarSenha2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/olho_riscado.png"))); // NOI18N

        btnCadastrar.setBackground(new java.awt.Color(63, 81, 181));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorderPainted(false);
        btnCadastrar.setFocusPainted(false);
        btnCadastrar.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnCadastrar.setOpaque(true);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(63, 81, 181));
        btnVoltar.setText("<html><u>Voltar ao Login</u></html>");
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setFocusPainted(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addComponent(jLabel1)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btnMostrarSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRegraTamanho)
                    .addComponent(lblRegraMaiuscula)
                    .addComponent(lblRegraMinuscula)
                    .addComponent(lblRegraNumero)
                    .addComponent(lblRegraEspecial)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btnMostrarSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
            .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarSenha1))
                .addGap(8, 8, 8)
                .addComponent(lblRegraTamanho)
                .addGap(3, 3, 3)
                .addComponent(lblRegraMaiuscula)
                .addGap(3, 3, 3)
                .addComponent(lblRegraMinuscula)
                .addGap(3, 3, 3)
                .addComponent(lblRegraNumero)
                .addGap(3, 3, 3)
                .addComponent(lblRegraEspecial)
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarSenha2))
                .addGap(30, 30, 30)
                .addComponent(btnCadastrar)
                .addGap(14, 14, 14)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private final com.saam.gestao.service.AuthService authService = new com.saam.gestao.service.AuthService();

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String senha = new String(txtSenha.getPassword());
        String confirmacao = new String(txtConfirmarSenha.getPassword());

        if (!senha.equals(confirmacao)) {
            javax.swing.JOptionPane.showMessageDialog(this, "As senhas informadas não coincidem.",
                "Validação", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            authService.cadastrar(txtNome.getText(), txtEmail.getText(), senha);
            javax.swing.JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso! Faça login.",
                "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            new com.saam.gestao.view.LoginView().setVisible(true);
            this.dispose();
        } catch (com.saam.gestao.exception.ValidationException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(),
                "Não foi possível cadastrar", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (com.saam.gestao.exception.DatabaseException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(),
                "Erro de conexão", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new com.saam.gestao.view.LoginView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JToggleButton btnMostrarSenha1;
    private javax.swing.JToggleButton btnMostrarSenha2;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRegraEspecial;
    private javax.swing.JLabel lblRegraMaiuscula;
    private javax.swing.JLabel lblRegraMinuscula;
    private javax.swing.JLabel lblRegraNumero;
    private javax.swing.JLabel lblRegraTamanho;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
