/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.saam.gestao.view;

/**
 *
 * @author Guilherme
 */
public class FuncionarioView extends javax.swing.JFrame {

    /**
     * Creates new form FuncionarioView
     */
    private static final int COLUNA_ACOES = 5;

    private java.util.List<com.saam.gestao.model.Funcionario> funcionariosExibidos = new java.util.ArrayList<>();
    private javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter;

    public FuncionarioView() {
        initComponents();
        com.saam.gestao.util.BordaArredondada.aplicar(txtNome, txtDataAdmissao, txtSalario);
        txtBusca.setOpaque(true);
        txtBusca.setBackground(java.awt.Color.WHITE);
        txtBusca.setBorder(new com.saam.gestao.util.BordaArredondada(10, new java.awt.Insets(6, 10, 6, 10)));
        // Excluir so aparece com um funcionario selecionado; o espaco fica reservado para os outros botoes nao se moverem
        ((javax.swing.GroupLayout) pnlForm.getLayout()).setHonorsVisibility(btnExcluir, false);
        btnExcluir.setVisible(false);
        setLocationRelativeTo(null);
        carregarTabela();

        txtBusca.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                aplicarFiltro();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                aplicarFiltro();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                aplicarFiltro();
            }
        });

        tblFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int viewCol = tblFuncionarios.columnAtPoint(evt.getPoint());
                int viewRow = tblFuncionarios.rowAtPoint(evt.getPoint());
                if (viewRow < 0 || viewCol < 0) {
                    return;
                }
                if (tblFuncionarios.convertColumnIndexToModel(viewCol) != COLUNA_ACOES) {
                    return;
                }
                int modelRow = tblFuncionarios.convertRowIndexToModel(viewRow);
                com.saam.gestao.model.Funcionario f = funcionariosExibidos.get(modelRow);

                idSelecionado = f.getId();
                txtNome.setText(f.getNome());
                txtDataAdmissao.setText(f.getDataAdmissao().format(
                        java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                txtSalario.setText(f.getSalario().toPlainString());
                chkStatus.setSelected(f.isStatus());
                btnExcluir.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDataAdmissao = new com.saam.gestao.util.PlaceholderTextField("dd/mm/aaaa");
        jLabel4 = new javax.swing.JLabel();
        txtSalario = new com.saam.gestao.util.PlaceholderTextField("0.00");
        lblMoeda = new javax.swing.JLabel();
        chkStatus = new javax.swing.JCheckBox();
        btnSalvar = new com.saam.gestao.util.BotaoArredondado();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblBuscar = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão de Funcionários - Sistema de Gestão de Funcionários");
        setBackground(new java.awt.Color(238, 241, 251));
        setMinimumSize(new java.awt.Dimension(900, 620));

        pnlForm.setBackground(new java.awt.Color(255, 255, 255));
        pnlForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 208, 234)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(63, 81, 181));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Funcionários");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 39, 58));
        jLabel2.setText("Nome:");

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 39, 58));
        jLabel3.setText("Data de admissão:");

        txtDataAdmissao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDataAdmissao.setToolTipText("Formato: dd/MM/aaaa (ex: 10/01/2024)");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 39, 58));
        jLabel4.setText("Salário:");

        txtSalario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSalario.setToolTipText("Use ponto ou vírgula para decimais (ex: 3500.00)");

        lblMoeda.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMoeda.setForeground(new java.awt.Color(34, 39, 58));
        lblMoeda.setText("R$");

        chkStatus.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        chkStatus.setForeground(new java.awt.Color(34, 39, 58));
        chkStatus.setSelected(true);
        chkStatus.setText("ATIVO");

        btnSalvar.setBackground(new java.awt.Color(63, 81, 181));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorderPainted(false);
        btnSalvar.setFocusPainted(false);
        btnSalvar.setMargin(new java.awt.Insets(8, 16, 8, 16));
        btnSalvar.setOpaque(true);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(198, 40, 40));
        btnExcluir.setText("<html><u>Excluir selecionado</u></html>");
        btnExcluir.setBorderPainted(false);
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setFocusPainted(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(34, 39, 58));
        btnLimpar.setText("<html><u>Limpar Campos</u></html>");
        btnLimpar.setBorderPainted(false);
        btnLimpar.setContentAreaFilled(false);
        btnLimpar.setFocusPainted(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSair.setForeground(new java.awt.Color(198, 40, 40));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setToolTipText("Encerrar a sessão e voltar para a tela de login");
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.setFocusPainted(false);
        btnSair.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSair.setIconTextGap(8);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(34, 39, 58));
        lblBuscar.setText("Buscar:");

        txtBusca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBusca.setToolTipText("Buscar por nome, data, salário ou status");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(63, 81, 181));
        lblTotal.setText("Total de funcionários: 0");

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSair))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 240, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(chkStatus))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(txtDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 198, 220)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addGap(8, 8, 8)
                        .addComponent(lblMoeda)
                        .addGap(4, 4, 4)
                        .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, 160))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(20, 20, 20)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(btnSair))
                .addGap(34, 34, 34)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkStatus))
                .addGap(18, 18, 18)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lblMoeda)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 420));

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Data Admissão", "Salário", "Status", "Ações"
            }
        ));
        tblFuncionarios.setRowSelectionAllowed(false);
        tblFuncionarios.setRowHeight(24);
        jScrollPane1.setViewportView(tblFuncionarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBuscar)
                        .addGap(8, 8, 8)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTotal))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private final com.saam.gestao.service.FuncionarioService funcionarioService =
            new com.saam.gestao.service.FuncionarioService();
    private Long idSelecionado = null;

    private void carregarTabela() {
        funcionariosExibidos = funcionarioService.listarTodos();
        lblTotal.setText("Total de funcionários: " + funcionariosExibidos.size());

        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
                new Object[]{"ID", "Nome", "Data Admissão", "Salário", "Status", "Ações"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 0 ? Long.class : String.class;
            }
        };
        java.time.format.DateTimeFormatter fmt = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
        java.text.NumberFormat moeda = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("pt", "BR"));
        for (com.saam.gestao.model.Funcionario f : funcionariosExibidos) {
            modelo.addRow(new Object[]{
                    f.getId(), f.getNome(), f.getDataAdmissao().format(fmt),
                    moeda.format(f.getSalario()), f.isStatus() ? "Ativo" : "Inativo", ""
            });
        }
        tblFuncionarios.setModel(modelo);

        javax.swing.table.TableColumn colunaAcoes = tblFuncionarios.getColumnModel().getColumn(COLUNA_ACOES);
        colunaAcoes.setMinWidth(44);
        colunaAcoes.setMaxWidth(44);
        colunaAcoes.setCellRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            private final javax.swing.Icon icone =
                    new javax.swing.ImageIcon(getClass().getResource("/icons/editar.png"));

            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                javax.swing.JLabel label = (javax.swing.JLabel) super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);
                label.setText("");
                label.setIcon(icone);
                label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                label.setToolTipText("Editar");
                return label;
            }
        });

        sorter = new javax.swing.table.TableRowSorter<>(modelo);
        tblFuncionarios.setRowSorter(sorter);
        aplicarFiltro();
    }

    private void aplicarFiltro() {
        if (sorter == null) {
            return;
        }
        String termo = txtBusca.getText().trim();
        if (termo.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(javax.swing.RowFilter.regexFilter(
                    "(?i)" + java.util.regex.Pattern.quote(termo)));
        }
    }

    private void limparCampos() {
        txtNome.setText("");
        txtDataAdmissao.setText("");
        txtSalario.setText("");
        chkStatus.setSelected(true);
        idSelecionado = null;
        tblFuncionarios.clearSelection();
        btnExcluir.setVisible(false);
    }

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            java.time.LocalDate data = java.time.LocalDate.parse(txtDataAdmissao.getText().trim(),
                    java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            java.math.BigDecimal salario = new java.math.BigDecimal(
                    txtSalario.getText().trim().replace(",", "."));

            if (idSelecionado == null) {
                funcionarioService.cadastrar(txtNome.getText(), data, salario, chkStatus.isSelected());
            } else {
                funcionarioService.atualizar(idSelecionado, txtNome.getText(), data, salario, chkStatus.isSelected());
            }
            carregarTabela();
            limparCampos();
        } catch (java.time.format.DateTimeParseException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data inválida. Use o formato dd/MM/aaaa.",
                    "Validação", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Salário inválido. Use apenas números (ex: 3500.00).",
                    "Validação", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (com.saam.gestao.exception.ValidationException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Validação", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (com.saam.gestao.exception.DatabaseException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Erro de conexão", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (idSelecionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um funcionário na tabela primeiro.",
                    "Validação", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirmacao = javax.swing.JOptionPane.showConfirmDialog(this,
                "Deseja realmente excluir este funcionário?", "Confirmar exclusão",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
            try {
                funcionarioService.excluir(idSelecionado);
                carregarTabela();
                limparCampos();
            } catch (com.saam.gestao.exception.DatabaseException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(),
                        "Erro de conexão", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int confirmacao = javax.swing.JOptionPane.showConfirmDialog(this,
                "Deseja realmente sair?", "Confirmar saída",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
            new com.saam.gestao.view.LoginView().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblMoeda;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtDataAdmissao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
